version: "3"
services:
  code-verify:
    build: .
    volumes:
      - ./app:/app/app
      - ./tools:/app/tools
    ports:
      - "3000:3000"
    # networks:
    #   - backend
    depends_on:
      - mongo
  mongo:
    image: mongo
    # networks:
    #   - backend
    volumes:
      - ./db:/data/db

networks:
  backend: