version: "3"
services:
  code-verify:
    build: .
    ports:
      - "80:3002"
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    image: mongo
    networks:
      - backend
    volumes:
      - ./db:/data/db

networks:
  backend: