version: "3"
services:
  code-battle:
    image: frontspot/code-battle
    network_mode: "host"
    depends_on:
      - code-verify
  code-verify:
    image: uladzimir/code-verify
    ports:
      - "3000:3002"
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    image: mongo
    networks:
      - backend
    volumes:
      - ./db:/data/db

networks:
  backend:
